/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as ApiPublicPrintWebhookRouteImport } from './routes/api/public/print-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPrintWebhookRoute = ApiPublicPrintWebhookRouteImport.update({
  id: '/api/public/print-webhook',
  path: '/api/public/print-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/menu/': typeof MenuIndexRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/api/public/print-webhook': typeof ApiPublicPrintWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/menu': typeof MenuIndexRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/api/public/print-webhook': typeof ApiPublicPrintWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/menu/': typeof MenuIndexRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/api/public/print-webhook': typeof ApiPublicPrintWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/basket'
    | '/checkout'
    | '/order-confirmation'
    | '/admin'
    | '/kitchen'
    | '/menu/$slug'
    | '/menu/'
    | '/account/orders'
    | '/api/public/print-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/basket'
    | '/checkout'
    | '/order-confirmation'
    | '/admin'
    | '/kitchen'
    | '/menu/$slug'
    | '/menu'
    | '/account/orders'
    | '/api/public/print-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/basket'
    | '/checkout'
    | '/order-confirmation'
    | '/_authenticated/admin'
    | '/_authenticated/kitchen'
    | '/menu/$slug'
    | '/menu/'
    | '/_authenticated/account/orders'
    | '/api/public/print-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BasketRoute: typeof BasketRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  MenuSlugRoute: typeof MenuSlugRoute
  MenuIndexRoute: typeof MenuIndexRoute
  ApiPublicPrintWebhookRoute: typeof ApiPublicPrintWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/print-webhook': {
      id: '/api/public/print-webhook'
      path: '/api/public/print-webhook'
      fullPath: '/api/public/print-webhook'
      preLoaderRoute: typeof ApiPublicPrintWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BasketRoute: BasketRoute,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  MenuSlugRoute: MenuSlugRoute,
  MenuIndexRoute: MenuIndexRoute,
  ApiPublicPrintWebhookRoute: ApiPublicPrintWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
